set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE dynamic)
set(VCPKG_PLATFORM_TOOLSET v142)

if(PORT STREQUAL "opentelemetry-cpp" OR PORT STREQUAL "protobuf")
	set(VCPKG_LIBRARY_LINKAGE static)
endif()