set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE dynamic)
set(VCPKG_PLATFORM_TOOLSET v142)
set(VCPKG_CMAKE_SYSTEM_VERSION 10.0.17134.0)

if(PORT STREQUAL "opentelemetry-cpp" OR PORT STREQUAL "protobuf")
	set(VCPKG_LIBRARY_LINKAGE static)
endif()